from enum import Enum
from TeamFightTacticsBot.Structures.Item import Item
from TeamFightTacticsBot.Enumerators.ItemEnhancements import ItemEnhancements


class Items(Enum):
    BFSWORD = Item("BFSword", None, None, ItemEnhancements.ATTACK_DAMAGE)
    RECURVEBOW = Item("RecurveBow", None, None, ItemEnhancements.ATTACK_SPEED)
    NEEDLESSLYLARGEROD = Item("NeedlesslyLarheRod", None, None, ItemEnhancements.ABILITY_POWER)
    TEAROFTHEGODDESS = Item("TearOfTheGoddess", None, None, ItemEnhancements.MANA)
    CHAINVEST = Item("ChainVest", None, None, ItemEnhancements.ARMOR)
    NEGATRONCLOAK = Item("NegatronCloak", None, None, ItemEnhancements.MAGICRESIST)
    GIANTSBELT = Item("GiantsBelt", None, None, ItemEnhancements.HEALTH)
    SPATULA = Item("Spatula", None, None, ItemEnhancements.SPATULA)
    INFINITYEDGE = Item("InfinityEdge", BFSWORD, BFSWORD, None)
    SWORDOFTHEDIVINE = Item("SwordOfTheDivine", BFSWORD, RECURVEBOW, None)
    HEXTECHGUNBLADE = Item("HextechGunBlade", BFSWORD, NEEDLESSLYLARGEROD, None)
    SPEAROFSHOJIN = Item("SpearOfShojin", BFSWORD, TEAROFTHEGODDESS, None)
    GUARDIANSANGEL = Item("GuardiansAngel", BFSWORD, CHAINVEST, None)
    THEBLOODTHIRSTER = Item("TheBloodThirster", BFSWORD, NEGATRONCLOAK, None)
    ZEKESHERALD = Item("ZekesHerald", BFSWORD, GIANTSBELT, None)
    YOUMUUSGHOSTBLADE = Item("YoumuusGhostblade", BFSWORD, SPATULA, None)
    RAPIDFIRECANNON = Item("RapidFireCannon", RECURVEBOW, RECURVEBOW, None)
    GUINSOOSRAGEBLADE = Item("GuinsoosRageblade", RECURVEBOW, NEEDLESSLYLARGEROD, None)
    STATIKKSHIV = Item("StatikkShiv", RECURVEBOW, TEAROFTHEGODDESS, None)
    PHANTOMDANCER = Item("PhantomDancer", RECURVEBOW, CHAINVEST, None)
    CURSEDBLADE = Item("CursedBlade", RECURVEBOW, NEGATRONCLOAK, None)
    TITANICHYDRA = Item("TitanicHydra", RECURVEBOW, GIANTSBELT, None)
    BLADEOFTHERUINEDKING = Item("BladeOfTheRuinedKing", RECURVEBOW, SPATULA, None)
    RABADONSDEATHCAP = Item("RabadonsDeathcap", NEEDLESSLYLARGEROD, NEEDLESSLYLARGEROD, None)
    LUDENSECHO = Item("LudensEcho", NEEDLESSLYLARGEROD, TEAROFTHEGODDESS, None)
    LOCKETOFTHEIRONSOLARI = Item("LocketOfTheIronSolari", NEEDLESSLYLARGEROD, CHAINVEST, None)
    IONICSPARK = Item("IonicSpark", NEEDLESSLYLARGEROD, NEGATRONCLOAK, None)
    MORELLONOMICON = Item("Morellonomicon", NEEDLESSLYLARGEROD, GIANTSBELT, None)
    YUUMI = Item("Yuumi", NEEDLESSLYLARGEROD, SPATULA, None)
    SERAPHSEMBRACE = Item("SeraphsEmbrace", TEAROFTHEGODDESS, TEAROFTHEGODDESS, None)
    FROZENHEART = Item("FrozenHeart", TEAROFTHEGODDESS, CHAINVEST, None)
    HUSH = Item("Hush", TEAROFTHEGODDESS, NEGATRONCLOAK, None)
    REDEMPTION = Item("Redemption", TEAROFTHEGODDESS, GIANTSBELT, None)
    DARKIN = Item("Darkin", TEAROFTHEGODDESS, SPATULA, None)
    THORNMAIL = Item("Thornmail", CHAINVEST, CHAINVEST, None)
    SWORDBREAKER = Item("SwordBreaker", CHAINVEST, NEGATRONCLOAK, None)
    REDBUFF = Item("RedBuff", CHAINVEST, GIANTSBELT, None)
    KNIGHTSVOW = Item("KnightsVow", CHAINVEST, SPATULA, None)
    DRAGONSCLAW = Item("DragonsClaw", NEGATRONCLOAK, NEGATRONCLOAK, None)
    ZEPHYR = Item("Zephyr", NEGATRONCLOAK, GIANTSBELT, None)
    RUNAANSHURRICANE = Item("RunaansHurricane", NEGATRONCLOAK, SPATULA, None)
    WARMOGSARMOR = Item("WarmogsArmor", GIANTSBELT, GIANTSBELT, None)
    FROZENMALET = Item("FrozenMalet", GIANTSBELT, SPATULA, None)
    FORCE_OF_NATURE = Item("ForceOfNature", SPATULA, SPATULA, None)
