CAROUSEL_CHAMPION_COUNT = 9
BENCH_SLOTS = 9
BOARD_SIZE_WIDTH = 7
BOARD_SIZE_HEIGHT = 3
STREAK_BONUS_GOLD_THRESHOLD = [2, 4, 7]


def variables_initialize():
    global CAROUSEL_CHAMPION_COUNT
    global BENCH_SLOTS
    global BOARD_SIZE_WIDTH
    global BOARD_SIZE_HEIGHT
    global STREAK_BONUS_GOLD_THRESHOLD
